name: postbuild

on:
  workflow_dispatch:
    inputs:
      hash_secret:
        description: 'Hash secret'
        required: true
        type: string
        default: ""

      version: 
        description: 'New app version'
        required: true
        type: string
        default: ""

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Send request
      run: |
        echo "secret: ${{ inputs.hash_secret }} version: ${{ inputs.version }}"
